---
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
  - directory: "/cloudrun-malware-scanner"
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
  - directory: "/cloudrun-malware-scanner"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
version: 2
...
